### ISSUE TITLE
Nd missions 

### ISSUE THREAD

**Issue by Rassinant** [AlPepino/Next-Days#6]
hello, how to enable the display option on VanillaPlusPlusMap? ND Missions.Thanks!

**Comment by Snowmanko** [comment]
Install https://steamcommunity.com/sharedfiles/filedetails/?id=1957554662, enjoy!

**Comment by Rassinant** [comment]
Привет поменял цвет хим защиты
ванильная работает а новая нет, в чем может быть проблема и как ее решить?

**Comment by Rassinant** [comment]
защита от газа есть ванильного а от радиации нет, хотя настройки никакие не менял
